import {
  Camera,
  Cpu,
  Bell,
  Thermometer,
  Lock,
  Car,
  Factory,
  HeartPulse,
  BatteryCharging,
  Cloud,
  Watch,
  ScanBarcode,
  Phone,
  Fan,
  Bot,
  CircuitBoard,
  Projector,
  Shield,
  Wifi,
  Gamepad2,
  HouseWifi,
  Laptop,
  Lightbulb,
  Monitor,
  Network,
  PlugZap,
  Printer,
  Radio,
  Router,
  Server,
  Smartphone,
  Sparkles,
  Speaker,
  Tablet,
  Tv,
  Tv2,
} from "lucide-react";
import type { DeviceType } from "@/lib/devices";
import { normalizeDeviceType } from "@/lib/devices";
import { cn } from "@/lib/utils";

/** Icono por tipo de dispositivo, compartido por tarjetas, filtros y detalle. */
export const deviceTypeIcons: Record<DeviceType, React.ComponentType<{ className?: string }>> = {
  pc: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  tv: Tv,
  "set-top-box": Tv2,
  console: Gamepad2,
  "home-assistant": HouseWifi,
  router: Router,
  nas: Server,
  printer: Printer,
  camera: Camera,
  "smart-plug": PlugZap,
  "smart-bulb": Lightbulb,
  "led-strip": Sparkles,
  speaker: Speaker,
  iot: Radio,
  "streaming-dongle": Tv2,
  "media-player": Tv2,
  projector: Projector,
  "audio-player": Speaker,
  amplifier: Speaker,
  radio: Radio,
  "photo-frame": Monitor,
  "photo-camera": Camera,
  "ip-phone": Phone,
  "barcode-scanner": ScanBarcode,
  scanner: Printer,
  smartwatch: Watch,
  clock: Watch,
  sensor: Radio,
  doorbell: Bell,
  "smart-appliance": PlugZap,
  "smart-fridge": PlugZap,
  "smart-washer": PlugZap,
  "robot-vacuum": Bot,
  thermostat: Thermometer,
  "air-conditioner": Fan,
  "smart-fan": Fan,
  "touch-panel": Tablet,
  controller: HouseWifi,
  "weather-station": Thermometer,
  "solar-panel": PlugZap,
  "smart-lock": Lock,
  "baby-monitor": Camera,
  "garage-door": HouseWifi,
  robot: Bot,
  switch: Network,
  "access-point": Wifi,
  "wifi-extender": Wifi,
  "mesh-node": Wifi,
  modem: Router,
  firewall: Shield,
  vpn: Shield,
  "network-appliance": Network,
  ups: BatteryCharging,
  server: Server,
  "virtual-machine": Monitor,
  "cloud-device": Cloud,
  "circuit-board": CircuitBoard,
  arduino: Cpu,
  "raspberry-pi": Cpu,
  rfid: ScanBarcode,
  car: Car,
  automotive: Car,
  industrial: Factory,
  medical: HeartPulse,
  energy: PlugZap,
  other: Network,
};

export function DeviceTypeIcon({ type, className }: { type: DeviceType; className?: string }) {
  const Icon = deviceTypeIcons[type] ?? deviceTypeIcons[normalizeDeviceType(type)] ?? Network;
  return <Icon className={cn("size-4", className)} />;
}
